version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:<< parameters.node_version >>
    parameters:
      node_version:
        type: string
    steps:
      - checkout
      - run:
          name: test stuff
          command: echo "Test complete on matrix << parameters.node_version >>"

workflows:
  version: 2
  test-matrix:
    jobs:
      - test:
          matrix:
            parameters:
              node_version: ["14", "16", "18"]