version: 2.1

parameters:
  environment:
    type: string
    default: "staging"

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: "Build Application"
          command: |
            echo "Building in << pipeline.parameters.environment >> environment"
  deploy:
    parameters:
      environment:
        type: string
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "Deploying to << parameters.environment >> environment"

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - build
      - deploy:
          environment: production
          requires:
            - build